apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/hyperkube-amd64:v__K8S_VERSION__
    command:
      - /hyperkube
      - apiserver
      - --bind-address=0.0.0.0
      - --insecure-bind-address=__MASTER_IP__
      - --etcd-servers=http://127.0.0.1:2379
      - --allow-privileged=true
      - --anonymous-auth=false
      - --service-cluster-ip-range=__K8S_SERVICE_SUBNET__
      - --secure-port=443
      - --advertise-address=__MASTER_IP__
      - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
      - --tls-cert-file=/etc/kubernetes/tls/apiserver.pem
      - --tls-private-key-file=/etc/kubernetes/tls/apiserver-key.pem
      - --client-ca-file=/etc/kubernetes/tls/ca.pem
      - --service-account-key-file=/etc/kubernetes/tls/apiserver-key.pem
      - --runtime-config=extensions/v1beta1=true,extensions/v1beta1/networkpolicies=true,batch/v2alpha1=true
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/tls
      name: tls-certs-kubernetes
      readOnly: true
    - mountPath: /etc/tls/certs
      name: tls-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/tls
    name: tls-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: tls-certs-host